services:
  - name: techTutorBackend
    type: web
    runtime: dotnet
    branch: main
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/TechTutorBackend.dll
    plan: free
